#!/bin/bash

curl -sL https://repos.influxdata.com/influxdb.key | sudo apt-key add -
source /etc/lsb-release
echo "deb https://repos.influxdata.com/${DISTRIB_ID,,} ${DISTRIB_CODENAME} stable" | sudo tee /etc/apt/sources.list.d/influxdb.list

sudo apt update
sudo apt install telegraf

sudo systemctl enable telegraf
sudo systemctl stop telegraf

sudo mv /etc/telegraf/telegraf.conf /etc/telegraf/telegraf.conf.orig
wget -O /etc/telegraf/telegraf.conf http://aurora.fiora.li/wget/telegraf.conf

sudo systemctl start telegraf
