services:
- docker:dind

variables:
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375
  KUBECONFIG: /tmp/config

stages:
  - build_and_push_frame
  - build_and_push_helper
  - deploy_to_production


build_and_push_frame:
  stage: build_and_push_frame
  image: docker:latest
  script:
    - cd frame
    - docker build --network host -t registry.fiora.li/photoframe:latest .
    - docker push registry.fiora.li/photoframe

build_and_push_helper:
  stage: build_and_push_helper
  image: docker:latest
  script:
    - cd frame
    - docker build --network host -t registry.fiora.li/photoframe_helper:latest .
    - docker push registry.fiora.li/photoframe_helper

deploy_to_production:
  stage: deploy_to_production
  image: bitnami/kubectl
  script:
    - echo ${kube_config} | base64 -d > "${KUBECONFIG}"
    - kubectl config use-context microk8s
    - kubectl rollout restart deployment/photoframe -nphotoframe
    - kubectl rollout restart deployment/photoframe-helper -nphotoframe
