<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>PhotoFrame - Admin Page</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" type="text/css" href="vendor/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="vendor/fontawesome/css/fontawesome-all.min.css">

    <!-- Custom styles for this template -->
    <link rel="stylesheet" type="text/css" href="css/admin.css">

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container">
            <a class="navbar-brand" href="/admin">Photo Frame</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="/admin">Home
                            <span class="sr-only">(current)</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/admin/photomanagement">Photo Management</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Configuration</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Usage</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <!-- Page Content -->
    <div class="container">

        <!-- Jumbotron Header -->
        <header class="jumbotron my-4">
            <h1 class="display-3">Welcome to the Admin page!</h1>
            <p class="lead">Here you can upload photos, remove existing photos, alter settings on the server, and view usage stats</p>
            <a href="/" class="btn btn-primary btn-lg">Access the Photo Frame</a>
        </header>

        <!-- Page Features -->
        <div class="row text-center">

            <div class="col-lg-4 col-md-6 mb-4">
                <div class="card">
                    <div class="card-img-top">
                        <a href="/admin/photoManagement" class="text-orange btn">
                            <i class="fas fa-images fa-7x" aria-hidden="true"></i>
                        </a>
                    </div>
                    <div class="card-body">
                        <h4 class="card-title">Photo Management</h4>
                        <p class="card-text">One stop shop for managing photos on the server. Here you can add, delete, or modify existing photos</p>
                    </div>
                </div>
            </div>

            <div class="col-lg-4 col-md-6 mb-4">
                <div class="card">
                    <div class="card-img-top">
                        <a href="#" class="text-aqua btn">
                            <i class="fas fa-cogs fa-7x" aria-hidden="true"></i>
                        </a>
                    </div>
                    <div class="card-body">
                        <h4 class="card-title">Configuration</h4>
                        <p class="card-text">Here you can change the server settings. These options include API keys for third parties, database credentials, and more.</p>
                    </div>
                </div>
            </div>

            <div class="col-lg-4 col-md-6 mb-4">
                <div class="card">
                    <div class="card-img-top">
                        <a href="#" class="text-red btn">
                            <i class="fas fa-chart-area fa-7x" aria-hidden="true"></i>
                        </a>
                    </div>
                    <div class="card-body">
                        <h4 class="card-title">Usage</h4>
                        <p class="card-text">Intrested in knowing how often the photo frame is being accessed? Wonder no longer!</p>
                    </div>
                </div>
            </div>

        </div>
        <!-- /.row -->

    </div>
    <!-- /.container -->

    <!-- Footer -->
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; Photo Frame</p>
        </div>
        <!-- /.container -->
    </footer>

    <!-- Base JavaScript Library -->
    <?php $this->assets->outputJs(); ?>

</body>

</html>