<html lang="en">

<head>
	<title>Fiorali Forecast</title>

	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="apple-mobile-web-app-capable" content="yes">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />

	<link rel="stylesheet" type="text/css" href="vendor/weathericons/css/weather-icons.min.css">
	<link rel="stylesheet" type="text/css" href="vendor/weathericons/css/weather-icons-wind.min.css">
	<link rel="stylesheet" type="text/css" href="vendor/fontawesome/css/fontawesome-all.min.css">
	<link rel="stylesheet" type="text/css" href="vendor/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="css/aurora.css">
	<link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
	<link rel="icon" href="/favicon.ico" type="image/x-icon">

	<!-- Base JavaScript Library -->
	<?php $this->assets->outputJs('librariesCollection'); ?>
	<?php $this->assets->outputJs('baseCollection'); ?>
	<?php $this->assets->outputJs('auroraJS'); ?>

</head>

<body onload="startTime(false)">
	<div id="backgroundTop">
		<div id="backgroundImage1" class="backgroundTop"></div>
		<div id="backgroundImage2" class="backgroundTop"></div>
		<div id="alert" class="alert" data-toggle="modal" data-target="#ErrorModal"><i class="fas fa-exclamation-triangle"></i></div>
		<div id="backgroundTopSummary" class="backgroundTopSummary">
			<span id="topClock" class="topClock"></span>
			<span id="topLocation" class="topLocation"></span>
			<span id="apparentTemperature" class="apparentTemperature"></span>
			<span><i id="topWeatherIcon" class="wi topWeatherIcon" aria-hidden="true"></i></span>
		</div>
	</div>
	<div id="selectorBar" class="selectorBar"></div>
	<div id="backgroundBottom" class="backgroundBottom"></div>

	<!-- Modal -->
	<div class="modal fade" id="ErrorModal" tabindex="-1" role="dialog" aria-labelledby="errorModal" aria-hidden="true">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
				<div class="modal-header">
					<h5 class="modal-title" id="errorModal">Troubleshooting</h5>
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
				</div>
				<div class="modal-body">
					<div class="modal-body-label">
						It appears as though there was an error. Please follow the steps below in order to resolve it:
					</div>
					<div id="errors" class="errors">
					</div>
				</div>
				<div class="modal-footer">
					<button id="closeButton" type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
					<button id="forceRefreshButton" type="button" class="btn btn-primary" onClick="window.location.reload();">Force Refresh</button>
				</div>
			</div>
		</div>
	</div>
</body>

</html>