<!DOCTYPE html>
<html lang="en">

	<head>

		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<meta name="description" content="">
		<meta name="author" content="">

		<title>PhotoFrame - Admin Page</title>

		<!-- CSS -->
		<?php $this->assets->outputCss(); ?>

	</head>

	<body>

		<!-- Navigation -->
		<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
			<div class="container">
				<a class="navbar-brand" href="/admin">Photo Frame</a>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="collapse navbar-collapse" id="navbarResponsive">
					<ul class="navbar-nav ml-auto">
						<li class="nav-item active">
							<a class="nav-link" href="/admin">Home
								<span class="sr-only">(current)</span>
							</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="/admin/photoManagement">Photo Management</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="#">Configuration</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="#">Usage</a>
						</li>
					</ul>
				</div>
			</div>
		</nav>

		<!-- Page Content -->
		<div class="container">

			<!-- Page Features -->
			<div class="row my-4 mb-4">
				<div class="col-lg-6 col-md-6">
					<h1>Add Photo</h1>
					<form class="my-4" name="form_upload">
						<div class="form-group">
							<label for="image_add">Select image to upload</label>
							<!--  -->
							<input type="file" class="form-control" id="image_add" onchange="uploadPreview(this)">
						</div>
						<div class="form-group">
							<label for="location">Location</label>
							<input type="text" class="form-control" id="location_upload">
						</div>
						<div class="form-group">
							<label for="date_taken">Date taken</label>
							<input type="date" class="form-control" id="date_taken_upload" value="{{ now }}">
						</div>
						<button id="submit_upload" class="btn btn-success" onchange="getBaseUrl()" onClick="getBaseUrl()">Upload</button>
					</form>
				</div>

				<div class="col-lg-4 col-md-6">
					<h1>Image Preview</h1>
					<div id="image_preview_add" style="width:{{ image_width }}px; height:{{ image_height }}px"></div>
				</div>
			</div>
			<!-- /.row -->

			<div class="row my-4 mb-4">
				<div class="col-lg-6 col-md-6">
					<h1>Modify Photo</h1>
					<form class="my-4" action="photomanagement/modify" method="POST" enctype="multipart/form-data">
						<div class="form-group">
							<label for="image_modify">Select image to modify</label>
							<select class="form-control" id="image_modify" onchange="findPhoto(event,'modify')">
								{% for photo in db_photos %}
									<option value="{{ photo['id'] }}";>{{ photo['location'] }} - {{ photo['date_taken'] }}</option>
								{% endfor %}
							</select>
						</div>
						<div class="form-group">
							<label for="location">Location</label>
							<input type="text" class="form-control" id="location_modify">
						</div>
						<div class="form-group">
							<label for="date_taken">Date taken</label>
							<input type="date" class="form-control" id="date_taken_modify">
						</div>
						<button id="submit_modify" class="btn btn-primary" onclick="modifyPhoto(event, 'modify')">Modify</button>
					</form>
				</div>

				<div class="col-lg-4 col-md-6">
					<h1>Image Preview</h1>
					<div id="image_preview_modify" style="width:{{ image_width }}px; height:{{ image_height }}px"></div>
				</div>
			</div>
			<!-- /.row -->

			<div class="row my-4 mb-4">
				<div class="col-lg-6 col-md-6">
					<h1>Delete Photo</h1>
					<form class="my-4" action="admin/photomanagement/delete" method="POST" enctype="multipart/form-data">
						<div class="form-group">
							<label for="image_modify">Select image to delete</label>
							<select class="form-control" id="image_delete" onchange="findPhoto(event,'delete')">
								{% for photo in db_photos %}
									<option value="{{ photo['id'] }}">{{ photo['location'] }} - {{ photo['date_taken'] }}</option>
								{% endfor %}
							</select>
						</div>
						<button id="submit_delete" class="btn btn-danger" onclick="modifyPhoto(event, 'delete')">Delete</button>
					</form>
				</div>

				<div class="col-lg-4 col-md-6">
					<h1>Image Preview</h1>
					<div id="image_preview_delete" style="width:{{ image_width }}px; height:{{ image_height }}px"></div>
				</div>
			</div>
			<!-- /.row -->

		</div>
		<!-- /.container -->

		<!-- Footer -->
		<footer class="py-5 bg-dark">
			<div class="container">
				<p class="m-0 text-center text-white">Copyright &copy; Photo Frame</p>
			</div>
			<!-- /.container -->
		</footer>

		<!-- Base JavaScript Library -->
		<?php $this->assets->outputJs(); ?>

	</body>

</html>
