<html lang="en">

<head>
    <title>Fiorali Flights</title>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />

    <link rel="stylesheet" type="text/css" href="vendor/fontawesome/css/fontawesome-all.min.css">
    <link rel="stylesheet" type="text/css" href="vendor/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="vendor/flight.css">
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
    <link rel="icon" href="/favicon.ico" type="image/x-icon">

    <!-- Base JavaScript Libraries -->
    <?php $this->assets->outputJs(); ?>
</head>

<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <a class="navbar-brand" href="#"><i class="fas fa-plane-departure"></i> Fiorali Flights</a>
        <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="navbar-collapse collapse" id="navbarsExampleDefault" style="">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled" href="#">Disabled</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
                    <div class="dropdown-menu" aria-labelledby="dropdown01">
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                </li>
            </ul>
        </div>
    </nav>

    <main role="main" class="container">

        <div class="airport-codes">

            <div class="departing row">
                <div class="departing-code col">
                    <div class="row">
                        <div class="col text-center">
                            <h1 id="departure-airport">{{departure_airport}}</h1>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col text-center">
                            <p>Toronto, Ontario, Canada</p>
                        </div>
                    </div>
                </div>
            </div>

            <div class="arrow-down col d-flex justify-content-center">
                <i class="fas fa-arrow-down"></i>
            </div>

            <div class="arriving row">
                <div class="arrival-code col">
                    <div class="row">
                        <div class="col text-center">
                            <h1 id="arrival-airport">{{arrival_airport}}</h1>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col text-center">
                            <p>Miami, Florida, United States</p>
                        </div>
                    </div>
                </div>
            </div>

        </div>

        <div class="flight-data container">
            <div class="row">
                <div class="col-4">
                    <p>Departure:</p>
                </div>
                <div class="col">
                    Monday, June 3rd, 10:00PM
                </div>
            </div>
            <div class="row">
                <div class="col-4">
                    <p>Arrival:</p>
                </div>
                <div class="col">
                    Monday, June 3rd, 11:00PM
                </div>
            </div>
            <div class="row">
                <div class="col-4">
                    <p>Airspeed:</p>
                </div>
                <div class="col">
                    {{velocity}} m/s
                </div>
            </div>
            <div class="row">
                <div class="col-4">
                    <p>Altitude:</p>
                </div>
                <div class="col">
                    {{altitude}} m
                </div>
            </div>
        </div>

    </main>
</body>

</html>

<!-- sample: {"time":1559609559,"states":[["c05faf","GGN7374 ","Canada",1559609559,1559609559,-79.6859,43.6056,1173.48,false,104.14,219.59,12.35,null,1181.1,"2233",false,0]]} --!